### ISSUE TITLE
SCS & SCDF - Please update your tile so that it uses compiled components

### ISSUE THREAD

**Issue by kquan-work** [csterwa/scs-combined-board#4]
Problem - Some tiles are using uncompiled (vs compiled) components that may end up having different component versions but reuse the same fingerprint. In some cases, this collision ends up updating every VM on the foundation, rather than just the tile that was added. this ends up making the update go from 5min to 5hours, which naturally upsets the customer admins, as they don't know why this is happening.

For instructions on what to update, please visit this google doc: https://docs.google.com/document/d/1B6mI5yBajB6_3fTP2eTjVWOFhnpkqoQghwZJQv5PLLs/edit#

**Comment by kquan-work** [comment]
bump on this, any movement away from non-compiled components?

**Comment by csterwa** [comment]
Added a Slack conversation on the #spring-cloud-services channel about this request and our tiles: https://pivotal.slack.com/archives/C064Q28L9/p1541698086712800

**Comment by csterwa** [comment]
@kquan-work I've moved this to our new main repo (rather than my personal repo) to track this. I forgot to move this over when we switched to `pivotal-cf` org for Waffle.io boards.

https://github.com/pivotal-cf/spring-cloud-services/issues/145
